version: 2
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      # - run:
      #     name: Install node modules
      #     command: npm install
      - run:
          name: Remove cache
          command: rm -rf .cache/
      - run:
          name: Build
          command: npm run build
      - deploy:
          name: deploy on VPS
          # command: ssh -o "StrictHostKeyChecking no" lostart@68.183.29.77 "cd lostart-react; npm run build;"
          command: ssh -o "StrictHostKeyChecking no" lostart@182.160.154.210 "cd lostart-react; npm run build;"
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
