version: 2
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy
          command: git push https://${9192805dcc345fc7df1f6b497e06dcfe00582a97}@github.com/crystalmanner/lostart-react.git master
            # |
            # git config credential.helper 'cache --timeout=120'
            # git config user.email "crystalmanner130@outlook.com"
            # git config user.name "crystalmanner"
            # git commit --allow-empty -m "Trigger deployment"
            # git push https://${9192805dcc345fc7df1f6b497e06dcfe00582a97}@github.com/crystalmanner/lostart-react.git master
        #   command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
